### ISSUE TITLE
Hi, want to ask the pixel size, thankyou

### ISSUE THREAD

**Issue by yiyayada** [Jungjaewon/Reference_based_Skectch_Image_Colorization#1]
Hello, I want to quote your article training comparison experiment, can your article train 128*128 pixel data?when I train my 128*128 data, the model have wrong,think there is no need to change the model？THANK YOU VERY MUCH~~

**Comment by Jungjaewon** [comment]
Thanks for your issue. This research is not my article. I just implement this research by pytorch. The image size of this result is 256, 256. Please refer to https://arxiv.org/abs/2005.05207. If you want to train a model you must change model architecture. this code is only for 256256 haha. I am not an author of this research.
