### ISSUE TITLE
The tps_transformer will consume lots of time, Have you encountered a similar situation？

### ISSUE THREAD

**Issue by meiguoofa** [Jungjaewon/Reference_based_Skectch_Image_Colorization#3]
the time nearly 4 times as original training time

**Comment by Jungjaewon** [comment]
Sorry, I did not measure time for tps_transformer. To my memory, training time was fine empirically.

you should modify tps_transformation.py which have infinite while loop

Thanks for your interest

**Comment by meiguoofa** [comment]
Thank you
