### ISSUE TITLE
Testing steps?

### ISSUE THREAD

**Issue by jamie212** [Jungjaewon/Reference_based_Skectch_Image_Colorization#8]
Excuse me for the interruption, could you please provide the steps of testing?

**Comment by Jungjaewon** [comment]
Thanks for your interest of my repository. What is the meaning of the step? the step are described in the paper and code. If you have any questions, leave it to this thread!!! Thanks

**Comment by jamie212** [comment]
Sorry, I made a mistake. What I wanted to ask about was the methods of testing (like commands, for example)

**Comment by Jungjaewon** [comment]
Oh.. Sorry I miss "of testing".. I did not write code for testing. If you want to write the test code, you can refer training code to write the test code. just call the dataloader, do forward-propagation without back-propagation.

**Comment by jamie212** [comment]
Understood, thank you for your response! I will give it a try and ask you if I have any questions.
